### PR TITLE
Unformat item lore and name when serializing items

### LINKED ISSUE #4094: Hex codes aren't added to kits correctly
### Type of bug

Other unexpected behaviour

### `/ess version` output

>....=>.... [20:25:25 INFO]: CONSOLE issued server command: /ess version
>.... [20:25:25 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Purpur-1022 (MC: 1.16.5)
>.... [20:25:25 INFO]: EssentialsX version: 2.19.0-dev+99-1e0d7fb
>.... [20:25:25 INFO]: LuckPerms version: 5.3.13
>.... [20:25:25 INFO]: PlaceholderAPI version: 2.10.9
>.... [20:25:25 INFO]: Vault version: 1.7.3-b131
>.... [20:25:25 INFO]: EssentialsXChat version: 2.19.0-dev+99-1e0d7fb
>.... [20:25:25 INFO]: EssentialsXSpawn version: 2.19.0-dev+99-1e0d7fb
>.... [20:25:25 INFO]: Fetching version information...
>.... [20:25:25 INFO]: Update checking disabled in config.

### Server startup log

https://paste.gg/p/anonymous/02fd0035cd414651ac54d087de862f56

### EssentialsX config files

https://paste.gg/p/anonymous/46c2f85e7b6e49b0abeb6c14a0793e7f

### Error log (if applicable)

n/a

### Bug description

Hex codes aren't added correctly to a kit when using /createkit in-game 

### Steps to reproduce

1. get an item
2. run /itemname &#FF0000Test
3. run /createkit test 1
4. run /kit test

### Expected behaviour

i should get the item named test in red

### Actual behaviour

i get an item named "&xTest" where "test" is in black

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #4094

### CODE REVIEW

**Comment by JRoy** [comment]
after merge, new unformat methods should be used in #4048

File: Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java [hunk 1]
```diff
@@ -216,7 +217,7 @@ public String serialize(final ItemStack is, final boolean useResolvers) {
                         sb.append("|");
                     }
                     first = false;
-                    sb.append(s.replaceAll(" ", "_"));
+                    sb.append(FormatUtil.unformatString(s).replaceAll(" ", "_"));
```
Comment (Proximyst) [inline Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java]:
```suggestion
                    sb.append(FormatUtil.unformatString(s).replace(" ", "_"));
```

File: Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java [hunk 2]
```diff
@@ -203,7 +204,7 @@ public String serialize(final ItemStack is, final boolean useResolvers) {
         if (is.hasItemMeta()) {
             final ItemMeta meta = is.getItemMeta();
             if (meta.hasDisplayName()) {
-                sb.append("name:").append(meta.getDisplayName().replaceAll(" ", "_")).append(" ");
+                sb.append("name:").append(FormatUtil.unformatString(meta.getDisplayName()).replaceAll(" ", "_")).append(" ");
```
Comment (Proximyst) [inline Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java]:
```suggestion
                sb.append("name:").append(FormatUtil.unformatString(meta.getDisplayName()).replace(" ", "_")).append(" ");
```

**Review by Proximyst — CHANGES_REQUESTED** [review]

**Review by pop4959 — APPROVED** [review]
