### PR TITLE
still fixing the configurate pr

### LINKED ISSUE #5409: NullPointerException when running /baltop
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5514ffe6abd0465ab8a740718a53eb4a

### Error log (if applicable)

https://gist.github.com/Frumple/c4829613e9fbd8c3163a960621838352

### Bug description

/baltop has usually worked fine on our server, but at some point recently it stopped working and now prints a NullPointerException in the console. 

We did recently update from EssentialsX v2.19.7 to v2.20.0, so that could be a factor here, but I can't be 100% certain that the problem started happening after we updated.

### Steps to reproduce

1. Run /baltop

### Expected behaviour

/baltop should state something like "Ordering balances of 10,315 users, please wait...", and then a few moments later the players with the largest balances on the server should be shown.

### Actual behaviour

The "Ordering balances of 10,315 users, please wait..." message does appear, but no players or balances are shown. Instead the NullPointerException appears in the console.

### PR DESCRIPTION
**Pull request by JRoy**
fixes #5409

read patch notes

rebase and merge

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/UserData.java [hunk 1]
```diff
@@ -83,7 +82,7 @@ public final void reloadConfig() {
         config.load();
         try {
             holder = config.getRootNode().get(UserConfigHolder.class);
-        } catch (SerializationException e) {
+        } catch (Throwable e) {
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/UserData.java:85]: oh boy

**Review by mdcfe — APPROVED** [review]
