### PR TITLE
Fix further trade sign validation mismatches

### LINKED ISSUE #6107: Another trade signs duplication glitch
### Type of bug

Exploit

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=B6eB0S73CH

### Error log (if applicable)

https://pastebin.com/wAxAMU2a

### Bug description

Apologies in advance for reporting a bug here without knowing exactly how to reproduce it, but unfortunately, the issue is serious, and I would like to ask for your help. Some time ago, I reported a similar bug (#6072) that was fixed, but unfortunately, my players have found another bug that allows item duplication.

Players are using [Trade] signs where they intend to buy a specific item. Another player clicks on the sign with the intention to sell, but the money from the sign and the sold item are not deducted from the player. However, the number of sold items increases.

I'm attaching an excerpt from the trade.log, where a player created a buy sign (trade) with $14,973. After 20 seconds, the sign was destroyed with the exact same amount of $14,973, but the player managed to extract 2,093 diamonds from it.

Players can duplicate any items this way, as long as they have at least one unit of the item and some money to create a buy sign. Please help me resolve this issue.

### Steps to reproduce

As above. 

### Expected behaviour

Fix it. 

### Actual behaviour

Players duplicate whatever they want.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JRoy**
can never win with this

fixes #6107

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/signs/SignTrade.java [hunk 1]
```diff
@@ -268,37 +272,44 @@ protected final Trade getTrade(final ISign sign, final int index, final AmountTy
     }
 
     protected final void subtractAmount(final ISign sign, final int index, final Trade trade, final IEssentials ess) throws SignException {
+        subtractAmount(sign, index, trade, ess, false);
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/signs/SignTrade.java]: Is it worth removing the overloads so it's clear at the call site whether we're calling this for validation or for real?

**Review by mdcfe — APPROVED** [review]
