### PR TITLE
Fix NPE on webhooks messages with show-webhook-messages enabled

### LINKED ISSUE #4451: NPE when `chat.show-webhook-messages` is enabled and a webhook sends a message
### Discussed in https://github.com/EssentialsX/Essentials/discussions/4450

<div type='discussions-op-text'>

<sup>Originally posted by **MageFX** August  9, 2021</sup>
I am unable to find the origin of member? This is currently spamming my console constantly.
`[13:57:17 ERROR]: [net.essentialsx.dep.net.dv8tion.jda.api.JDA] One of the EventListeners had an uncaught exception
java.lang.NullPointerException: Cannot invoke "net.essentialsx.dep.net.dv8tion.jda.api.entities.Member.hasPermission(net.essentialsx.dep.net.dv8tion.jda.api.Permission[])" because "member" is null
        at net.essentialsx.discord.util.DiscordUtil.hasRoles(DiscordUtil.java:176) ~[?:?]
        at net.essentialsx.discord.listeners.DiscordListener.onGuildMessageReceived(DiscordListener.java:76) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:481) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
        at net.essentialsx.dep.net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
        at net.essentialsx.dep.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at net.essentialsx.dep.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at net.essentialsx.dep.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at net.essentialsx.dep.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at net.essentialsx.dep.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at net.essentialsx.dep.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at net.essentialsx.dep.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]`</div>

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #4451

### CODE REVIEW

File: EssentialsDiscord/src/main/java/net/essentialsx/discord/util/DiscordUtil.java [hunk 1]
```diff
@@ -138,9 +138,9 @@ private static void cleanWebhooks(final Guild guild, String webhookName) {
      * @return The highest role or blank string.
      */
     public static String getRoleFormat(Member member) {
-        final List<Role> roles = member.getRoles();
+        final List<Role> roles = member == null ? null :member.getRoles();
```
Comment (mdcfe) [inline EssentialsDiscord/src/main/java/net/essentialsx/discord/util/DiscordUtil.java]:
```suggestion
        final List<Role> roles = member == null ? null : member.getRoles();
```

**Review by mdcfe — CHANGES_REQUESTED** [review]

**Review by mdcfe — APPROVED** [review]
