### PR TITLE
Fix give command for tipped arrow item

### LINKED ISSUE #5580: /give tipped_arrow gives a potion instead
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=94c23f3e97ea428396ae3316dc80bfcc

### Error log (if applicable)

none

### Bug description

on the arrow - tipped_arrow 1 splash:false effect:slow power:1 duration:120 this command issues a potion slowing down by the action of 120 seconds, but should issue an arrow.
on the potion I have already done through the following command - potion:34 1 splash:false effect:speed power:1 duration:600 and it works, the potion is given what it needs. The only problem is with the arrow. About the arrow. I gave myself an arrow in the mine through this command / minecraft:give @p minecraft:tipped_arrow{Potion:"minecraft:water",CustomPotionEffects:[{Id:2,Duration:32000,ShowParticles:0b}] }
then I wrote the command /createkit test 0
Then I wrote / kit test, but potions turned out instead of arrows, although there should be arrows with the effect of slowing down for so many seconds of rank 1.

### Steps to reproduce

Combined follow the image
1: / minecraft:give @p minecraft:tipped_arrow{Potion:"minecraft:water",CustomPotionEffects:[{Id:2,Duration:32000,ShowParticles:0b} ] }
2: Says I did /createkit test 0
3: I prescribed the / kit test command, but in the end, instead of an arrow, a deceleration potion is issued.

### Expected behaviour

Combined follow the image
1: / minecraft:give @p minecraft:tipped_arrow{Potion:"minecraft:water",CustomPotionEffects:[{Id:2,Duration:32000,ShowParticles:0b} ] }
2: Says I did /createkit test 0
3: We expect the behavior to be issued a rank 1 arrow for 120 seconds

### Actual behaviour

A deceleration potion is issued instead of an arrow for deceleration

### PR DESCRIPTION
**Pull request by TiagoFar78**
### Information

This PR fixes #5580. 

### Details

**Proposed fix:**    

Fix for the problem where a player using the give command to get a tipped arrow with a specific effect gives a potion instead.

**Environments tested:**    

OS: Windows 11

Java version: JDK 17 

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**    

First I saw the bug report and tried to repruduce it. By using the command '/give @p tipped_arrow 1 splash:false effect:slow power:1 duration:120' I received a potion instead of the requested material (tipped_arrow). I looked into the code for a while and I noticed that this would happen every time the give command is requesting a tipped arrow as material and an effect by using "effect", "power" and "duration" arguments. This would happen because Essentials will convert any item that can have a spash property into a potion.

```
if (isSplashPotion && stack.getType() != Material.SPLASH_POTION) {
    stack.setType(Material.SPLASH_POTION);
} else if (!isSplashPotion && stack.getType() != Material.POTION) {
    stack.setType(Material.POTION);
}
```

I beleive this was to allow players to use 'splash:true' as argument so that players can say the material they are looking for is a potion. The right way to get a splash potion would be selecting 'splash_potion' as the material argument but it's much easier to remmeber to set the splash property. However, by doing this every other item with splash property would become a potion. To fix this I just considered the case where the material could be a tipped_arrow.

```
if (isSplashPotion && stack.getType() != Material.SPLASH_POTION && stack.getType() != Material.TIPPED_ARROW) {
    stack.setType(Material.SPLASH_POTION);
} else if (!isSplashPotion && stack.getType() != Material.POTION && stack.getType() != Material.TIPPED_ARROW) {
    stack.setType(Material.POTION);
}
```

After trying out the command with the new code I was able to receive a tipped arrow using the command '/give @p tipped_arrow 1 splash:false effect:slow power:1 duration:120'

image

### CODE REVIEW

**Comment by mdcfe** [comment]
Thanks for the PR! The fix generally looks good to me but I believe this will need an enum compat fix for versions of MC that don't support tipped arrows.

In the long term it would be good to properly support lingering potions, but that's an issue that I'm happy to have solved in a separate PR as it'll require larger changes.

**Comment by TiagoFar78** [comment]
I don't think I need to consider minecraft versions that don't support tipped arrows because when it reaches this point it already checked if it is running in a minecraft version that supports tipped arrows. These are the lines arround the fixed part:

```
if (VersionUtil.getServerBukkitVersion().isHigherThanOrEqualTo(VersionUtil.v1_9_R01)) {
    if (isSplashPotion && stack.getType() != Material.SPLASH_POTION && stack.getType() != Material.TIPPED_ARROW) {
        stack.setType(Material.SPLASH_POTION);
    } else if (!isSplashPotion && stack.getType() != Material.POTION && stack.getType() != Material.TIPPED_ARROW) {
        stack.setType(Material.POTION);
    }
} else {
    final Potion potion = Potion.fromDamage(stack.getDurability());
    potion.setSplash(isSplashPotion);
    potion.apply(stack);
}
```

File: Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java [hunk 1]
```diff
@@ -543,9 +543,9 @@ public void addPotionMeta(final CommandSource sender, final boolean allowShortNa
                 pmeta.addCustomEffect(pEffect, true);
                 stack.setItemMeta(pmeta);
                 if (VersionUtil.getServerBukkitVersion().isHigherThanOrEqualTo(VersionUtil.v1_9_R01)) {
-                    if (isSplashPotion && stack.getType() != Material.SPLASH_POTION) {
+                    if (isSplashPotion && stack.getType() != Material.SPLASH_POTION && stack.getType() != Material.TIPPED_ARROW) {
```
Comment (pop4959) [inline Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java]: This looks generally fine to me, but would prefer that you do a single check instead of two here. Can just wrap the whole if/elseif, which does add a layer of indentation but is clearer and I think that's more important.

**Review by pop4959 — CHANGES_REQUESTED** [review]

File: Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java (hunk 1 above)
Comment (pop4959) [reply Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java]: Alternatively we can probably avoid the entire thing by flipping the conditions here. E.g. check if isSplashPotion and the stash type is a regular potion, then convert to splash. And vice versa.

**Comment by pop4959** [comment]
Nit picking a little here, but as mdcfe mentioned, thank you for investigating, this code definitely looks like an obvious culprit to the issue here. And congrats on your first contribution!

File: Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java (hunk 1 above)
Comment (TiagoFar78) [reply Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java]: I though about flipping the conditions first but I didn't know if this would break anything or if it was just to let the players create a splash potion using splash:true. That's a nice one yeah.

I am relatively new to this kind of stuff... I am the one who is supposed to change the code right?

Comment (pop4959) [reply Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java]: Yeah I'm 99% sure that it is just to create a splash potion with splash:true.

Essentials is just really old so back then there were not any other potion-like items. Hence the bug now, caused by the conditions being set up here in a vague way. Should definitely be more explicit.

Is it possible it could break something? Maybe, but probably not imo. Either way this code just needs to be more robust. :p

**Review by pop4959 — APPROVED** [review]
Assuming this has been tested, LGTM 👍

**Review by mdcfe — APPROVED** [review]
