### PR TITLE
Move away from adventure-platform for Paper

### LINKED ISSUE #6215: Some MiniMessage tags are not working
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=icteJvcME9

### Error log (if applicable)

–

### Bug description

I have customized language files and used MiniMessages functionality in them. I recently updated the server to Minecraft 1.21.7 and EssentialsX too. When I migrated my old language file, I noticed that some tags of the MiniMessage no longer works, such as `<hover>` or `<click>`, but color formatting such as `<red>`, `<blue>` or `<#702963>` still working fine.

### Steps to reproduce

1. Change any line in the localization file to add a clickable/hoverable message through MiniMessage tags;
2. Start the server;
3. Join the server and call the modified line;
4. Try clicking/hovering over the message.

### Expected behaviour

Default behavior of `<hover>` and `<click>` tags.

### Actual behaviour

Nothing is happening.

### Additional Information

I used before version 1.21.4 of the Minecraft server with paper-1.21.4-232 and EssentialsX-2.21.0-dev and on this version all tags still work correctly.

### PR DESCRIPTION
**Pull request by JRoy**
Makes us no longer dependent on adventure-platform for Paper servers as we will use their native adventure apis.

Few hacks needed to be done to not remap things in places but this is the best we can do

The PaperAdventureFacet has to be in PaperProvider to avoid the kyori remapping that happens on the entire EssentialsX module (we already did this for PaperChatListenerProvider)

Fixes #6215

### CODE REVIEW

**Comment by sarahkittyy** [comment]
i pulled this pr's build artifact and i still cannot click on minimessage clickable links / see the hover msg

**Comment by JRoy** [comment]
> i pulled this pr's build artifact and i still cannot click on minimessage clickable links / see the hover msg

need an `/ess dump all`

**Comment by sarahkittyy** [comment]
https://essentialsx.net/dump.html?bytebin=j8AB75k9zg

**Comment by JRoy** [comment]
> [essentialsx.net/dump.html?bytebin=j8AB75k9zg](https://essentialsx.net/dump.html?bytebin=j8AB75k9zg)

thank you, can i also get the translation you are using (both the key and the actual translation line)

**Comment by sarahkittyy** [comment]
@JRoy how do i get that for you? i'm not familiar with this project i am just a user :)

**Comment by JRoy** [comment]
> @JRoy how do i get that for you? i'm not familiar with this project i am just a user :)

it would be any files in the `plugins/Essentials/messages` folder. This is where you would customize the messages to add hover events in the first place.

**Comment by sarahkittyy** [comment]
It's empty. I'm using https://github.com/HappyAreaBean/SimpleJoinMessage/ however the issue persists with /tellraw output as well

**Comment by JRoy** [comment]
> It's empty. I'm using [HappyAreaBean/SimpleJoinMessage](https://github.com/HappyAreaBean/SimpleJoinMessage/?rgh-link-date=2025-07-16T03%3A18%3A41Z) however the issue persists with /tellraw output as well

so you're saying that when you have essentials installed, sending a hover message with `/tellraw` doesn't even work?

**Comment by sarahkittyy** [comment]
yep! 
image

`/tellraw @a {"text":"testing 123","hoverEvent":{"action":"show_text","contents":"hover text"}}`

**Comment by JRoy** [comment]
> yep! image
> 
> `/tellraw @a {"text":"testing 123","hoverEvent":{"action":"show_text","contents":"hover text"}}`

This has nothing to do with Essentials, Mojang updated the format for JSON messages, so you need to do:

`/tellraw @a {"text":"testing 123","hover_event":{"action":"show_text","value":"hover text"}}`

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java [hunk 1]
```diff
@@ -756,16 +755,18 @@ public void handlePlayerCommandPreprocess(final PlayerCommandPreprocessEvent eve
...
                 if (!user.isAuthorized("essentials.chat.spy.exempt")) {
                     final String playerName = ess.getSettings().isSocialSpyDisplayNames() ? player.getDisplayName() : player.getName();
                     for (final User spyer : ess.getOnlineUsers()) {
                         if (spyer.isSocialSpyEnabled() && !player.equals(spyer.getBase())) {
-                            final Component base = (user.isMuted() && ess.getSettings().getSocialSpyListenMutedPlayers())
+                            final ComponentHolder base = (user.isMuted() && ess.getSettings().getSocialSpyListenMutedPlayers())
                                     ? spyer.tlComponent("socialSpyMutedPrefix")
                                     : spyer.tlComponent("socialSpyPrefix");
-                            spyer.sendComponent(base.append(AdventureUtil.legacyToAdventure(playerName)).append(Component.text(": " + event.getMessage())));
+                            final ComponentHolder append = ess.getAdventureFacet().legacyToAdventure(playerName + ": " + event.getMessage());
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java]: Do we want to include the message inside the `legacyToAdventure` call? This wasn't the case before

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java [hunk 2]
```diff
@@ -1025,6 +1028,10 @@ public void generateUidCache() {
     }
 
     public void upgradeLang() {
+        if (Essentials.TESTING) {
+            return;
+        }
+
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java]: Why was this added now?

File: Essentials/src/main/resources/messages.properties [hunk 3]
```diff
@@ -1135,14 +1135,14 @@ serverFull=Server is full\!
...
+serverUnsupported=<red>You are running an unsupported server version\!
+serverUnsupportedClass=<red>Status determining class\: {0}
+serverUnsupportedCleanroom=<dark_red>You are running a server that does not properly support Bukkit plugins that rely on internal Mojang code. Consider using an Essentials replacement for your server software.
+serverUnsupportedDangerous=<dark_red>You are running a server fork that is known to be extremely dangerous and lead to data loss. It is strongly recommended you switch to a more stable server software like Paper.
+serverUnsupportedLimitedApi=<red>You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.
+serverUnsupportedDumbPlugins=<dark_red>You are using plugins known to cause severe issues with EssentialsX and other plugins.
+serverUnsupportedMods=<dark_red>You are running a server that does not properly support Bukkit plugins. Bukkit plugins should not be used with Forge/Fabric mods\! For Forge\: Consider using ForgeEssentials, or SpongeForge + Nucleus.
```
Comment (mdcfe) [inline Essentials/src/main/resources/messages.properties]:
```suggestion
serverUnsupportedMods=<dark_red>You are running a server that does not properly support Bukkit plugins. Bukkit plugins should not be used with Forge/Fabric mods\! Remove your hybrid server jar, and use the FTB Essentials mod for similar features to EssentialsX.
```

This recommendation should also get updated on the wiki/website

File: Essentials/src/main/java/com/earth2me/essentials/Essentials.java [hunk 4]
```diff
@@ -591,16 +589,29 @@ public void reload() {
...
 
         final PluginManager pm = getServer().getPluginManager();
         registerListeners(pm);
 
-        AdventureUtil.setEss(this);
-        bukkitAudience = BukkitAudiences.create(this);
+        initAdventureFacet();
+    }
+
+    private void initAdventureFacet() {
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/Essentials.java:606]: It feels like this is what providers are for. Granted providers can't have parameters passed in right now, but if we need more facets like this in the future, it'd be nice to have one system handle this.

File: Essentials/src/main/java/com/earth2me/essentials/User.java [hunk 5]
```diff
@@ -547,7 +546,7 @@ public void setDisplayNick() {
     @Override
     public String getDisplayName() {
         //noinspection ConstantConditions
-        return super.getBase().getDisplayName() == null || (ess.getSettings().hideDisplayNameInVanish() && isHidden()) ? super.getBase().getName() : super.getBase().getDisplayName();
+        return super.getBase().getDisplayName() == null || ess.getSettings().hideDisplayNameInVanish() && isHidden() ? super.getBase().getName() : super.getBase().getDisplayName();
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/User.java]: I'd prefer not to have unrelated reformats in this PR

**Review by mdcfe — CHANGES_REQUESTED** [review]

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java (hunk 1 above)
Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java]: Component.text is no more

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java (hunk 2 above)
Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java]: so true

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java (hunk 1 above)
Comment (mdcfe) [reply Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java]: This still parses legacy codes in the message though where it didn't before though, no?

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java [hunk 6]
```diff
@@ -794,9 +794,10 @@ public void handlePlayerCommandPreprocess(final PlayerCommandPreprocessEvent eve
                             final ComponentHolder base = (user.isMuted() && ess.getSettings().getSocialSpyListenMutedPlayers())
                                     ? spyer.tlComponent("socialSpyMutedPrefix")
                                     : spyer.tlComponent("socialSpyPrefix");
-                            final ComponentHolder append = ess.getAdventureFacet().legacyToAdventure(playerName + ": " + event.getMessage());
+                            final ComponentHolder nameComponent = ess.getAdventureFacet().legacyToAdventure(playerName);
+                            final ComponentHolder messageComponent = ess.getAdventureFacet().text(": " + event.getMessage());
 
-                            spyer.sendComponent(ess.getAdventureFacet().append(base, append));
+                            spyer.sendComponent(ess.getAdventureFacet().append(ess.getAdventureFacet().append(base, nameComponent), messageComponent));
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java]: Can we have varargs on `.append`?

**Review by mdcfe — APPROVED** [review]
