### PR TITLE
fix: essentials.home.bed & essentials.sethome.bed permissions

### LINKED ISSUE #5963: The "essentials.home.bed" permission is ignored
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Dump is not needed here 

### Error log (if applicable)

_No response_

### Bug description

The essentials.home.bed and essentials.sethome.bed permissions simply don't work: if they are set to false, the player can still teleport to the bed via the /home bed command. 
Interesting behavior: when you disable essentials.home.bed, the "bed" disappears from the tab complete, but you can still teleport to the "bed" point. 

### Steps to reproduce

1. Denied the player the permission of essentials.home.bed and essentials.sethome.bed through luckperms 
2. Nothing helped 

### Expected behaviour

The player cannot teleport to the bed via the /home bed command if the essentials.home.bed permission is set to "false" 

### Actual behaviour

The player can use /home bed when the essentials.home.bed permission is in the "false" 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Hunh0w**
### Information

This PR fixes #5963. 

### Details

**Proposed fix:**   
If the player uses "/home bed" when he doesn't have the "essentials.home.bed" permission, he's getting a no permission error for it 

**Environments tested:**    

OS: Ubuntu 24.04.1 LTS

Java version: 21

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandhome.java [hunk 1]
```diff
@@ -73,10 +73,14 @@ public void run(final Server server, final User user, final String commandLabel,
                 final List<String> homes = finalPlayer.getHomes();
                 if (homes.isEmpty() && finalPlayer.equals(user)) {
                     if (ess.getSettings().isSpawnIfNoHome()) {
-                        final UserTeleportHomeEvent event = new UserTeleportHomeEvent(user, null, bed != null ? bed : finalPlayer.getWorld().getSpawnLocation(), bed != null ? UserTeleportHomeEvent.HomeType.BED : UserTeleportHomeEvent.HomeType.SPAWN);
-                        server.getPluginManager().callEvent(event);
-                        if (!event.isCancelled()) {
-                            user.getAsyncTeleport().respawn(charge, TeleportCause.COMMAND, getNewExceptionFuture(user.getSource(), commandLabel));
+                        if(bed == null || finalPlayer.isAuthorized("essentials.home.bed")){
```
Comment (pop4959) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandhome.java]: You should not be checking if the bed is null here, it is already checked below and has a defined behavior which this change appears to otherwise break.

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandhome.java [hunk 2]
```diff
@@ -73,10 +73,14 @@ public void run(final Server server, final User user, final String commandLabel,
...
+                            final UserTeleportHomeEvent event = new UserTeleportHomeEvent(user, null, bed != null ? bed : finalPlayer.getWorld().getSpawnLocation(), bed != null ? UserTeleportHomeEvent.HomeType.BED : UserTeleportHomeEvent.HomeType.SPAWN);
+                            server.getPluginManager().callEvent(event);
+                            if (!event.isCancelled()) {
+                                user.getAsyncTeleport().respawn(charge, TeleportCause.COMMAND, getNewExceptionFuture(user.getSource(), commandLabel));
+                            }
+                        }else {
```
Comment (pop4959) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandhome.java]: Please fix the indentation here and in other places in the code to match the code style

**Review by pop4959 — DISMISSED** [review]
Hey, thanks for making your first PR to Essentials! We appreciate it.

I left a few comments for you to look at. Please also share proof of testing (show before/after screenshot is probably the easiest) in the demonstration section which you left blank.

Also, in the original issue, `essentials.sethome.bed` is mentioned. Have you checked if there is a problem with /sethome or is this working as intended?

**Comment by Hunh0w** [comment]
Hey, thanks you too for your feedback ! ^^
I updated this PR according to your comments.

I added a fix for the `essentials.sethome.bed` there was a problem, we couldn't prevent player from setting his bed position even with this permission to false

Screenshots of the before behaviour:
Capture d’écran du 2024-12-12 09-03-19
Capture d’écran du 2024-12-12 10-11-26

Screenshots of the after behaviour:
Capture d’écran du 2024-12-12 10-09-24
no_bed_perm_result

For the bed sethome, if we don't have the permission it doesn't produce anything, maybe i should add an error message in this case ?

**Review by JRoy — APPROVED** [review]

**Comment by JRoy** [comment]
thanks!

**Comment by Potothingi** [comment]
Since this commit I can't sleep at night and can't set respawn point. Previous build (2.21.1-dev+18-3b0c229) was fine.
```
essentials.home: true
essentials.home.bed: true
```

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java [hunk 3]
```diff
@@ -823,12 +823,15 @@ public void onPlayerInteract(final PlayerInteractEvent event) {
...
-                    if (player.isAuthorized("essentials.sethome.bed") && player.getWorld().getEnvironment().equals(World.Environment.NORMAL)) {
+                    final boolean isAuthorized = player.isAuthorized("essentials.sethome.bed");
+                    if (isAuthorized && player.getWorld().getEnvironment().equals(World.Environment.NORMAL)) {
                         player.getBase().setBedSpawnLocation(event.getClickedBlock().getLocation());
                         // In 1.15 and above, vanilla sends its own bed spawn message.
                         if (VersionUtil.getServerBukkitVersion().isLowerThan(VersionUtil.v1_15_R01)) {
                             player.sendTl("bedSet", player.getLocation().getWorld().getName(), player.getLocation().getBlockX(), player.getLocation().getBlockY(), player.getLocation().getBlockZ());
                         }
+                    } else if (!isAuthorized) {
+                        event.setCancelled(true);
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java:834]: This prevents people interacting with the bed. Why was this changed?

Comment (Hunh0w) [reply Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java:834]: This was because if someone interact with a bed, they automatically set the bed home even if they don't have the permission
