### PR TITLE
Fix safelogin support with 1.18 world heights

### LINKED ISSUE #4665: Under y=0 Fly gets reenabled automatically
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c041cea1f72941fbbffdc7bad17c00d4

### Error log (if applicable)

_No response_

### Bug description

While opped, fly mode gets reenabled every time I rejoin the server under a certain y level. This does not happen normally, only under y=-1. This command "essentials.fly.safelogin" may be doing it, it describes itself as only enabling on rejoin if you're in the air, so I would assume that it thinks everything under y=-1 is void since 1.18 added new stuff.

### Steps to reproduce

1. Start as a server op.
2. Make a hole down to y=-1
3. Go into survival mode.
4. Make sure fly is already toggled off and try rejoining.

### Expected behaviour

It should log me back in without enabling fly mode unless I'm currently in the air.

### Actual behaviour

It thinks I'm in the void at y=-1 and below so it is always enabling fly regardless.

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #4665

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java [hunk 1]
```diff
@@ -267,7 +267,7 @@ public static boolean shouldFly(IEssentials ess, final Location loc) {
         int y = (int) Math.round(loc.getY());
         final int z = loc.getBlockZ();
         int count = 0;
-        while (LocationUtil.isBlockUnsafe(ess, world, x, y, z) && y > -1) {
+        while (LocationUtil.isBlockUnsafe(ess, world, x, y, z) && y > ess.getWorldInfoProvider().getMinHeight(world) - 1) {
```
Comment (kennytv) [inline Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java]: equal to or greater than moment?

Comment (mdcfe) [reply Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java]: ok

Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java]: too many space changes, applied manually

File: Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java [hunk 2]
```diff
@@ -267,7 +267,7 @@ public static boolean shouldFly(IEssentials ess, final Location loc) {
         int y = (int) Math.round(loc.getY());
         final int z = loc.getBlockZ();
         int count = 0;
-        while (LocationUtil.isBlockUnsafe(ess, world, x, y, z) && y > -1) {
+        while (LocationUtil.isBlockUnsafe(ess, world, x, y, z) && y <= ess.getWorldInfoProvider().getMinHeight(world)) {
```
Comment (kennytv) [inline Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java]: equal to or greater than moment??

Comment (mdcfe) [reply Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java]: copium

Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java]: I just downvoted your comment.

# FAQ

## What does this mean?

The amount of karma (points) on your comment and GitHub account has decreased by one.

## Why did you do this?

There are several reasons I may deem a comment to be unworthy of positive or neutral karma. These include, but are not limited to:

* Rudeness towards other GitHubers,
* Spreading incorrect information,
* Sarcasm not correctly flagged with a `/s`.

## Am I banned from the GitHub?

No - not yet. But you should refrain from making comments like this in the future. Otherwise I will be forced to issue an additional downvote, which may put your commenting and posting privileges in jeopardy.

## I don't believe my comment deserved a downvote. Can you un-downvote it?

Sure, mistakes happen. But only in exceedingly rare circumstances will I undo a downvote. If you would like to issue an appeal, shoot me a private message explaining what I got wrong. I tend to respond to GitHub PMs within several minutes. Do note, however, that over 99.9% of downvote appeals are rejected, and yours is likely no exception.

## How can I prevent this from happening in the future?

Accept the downvote and move on. But learn from this mistake: your behavior will not be tolerated on Reddit.com. I will continue to issue downvotes until you improve your conduct. Remember: Reddit is privilege, not a right.

Comment (mdcfe) [reply Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java]: This PR breaks my workflow! My setup works for me. Just add an option to reenable spacebar heating.

**Review by mdcfe — APPROVED** [review]
