### PR TITLE
[AntiBuild] Fix ender crystal breaking on 1.8

### LINKED ISSUE #4418: Essentials AntiBuild doesn't protect against player destruction of Ender Crystals
### Type of bug

Exploit

### `/ess version` output

[14:00:06 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[14:00:06 INFO]: Brand version: CraftBukkit
[14:00:06 INFO]: EssentialsX version: 2.19.0-dev+226-17e026f
[14:00:06 INFO]: PlaceholderAPI version: 2.10.4
[14:00:06 INFO]: Vault version: 1.7.3-b131
[14:00:06 INFO]: GroupManager version: 2.9 (Phoenix)
[14:00:06 INFO]: Citizens version: 2.0.28-SNAPSHOT (build 2358)
[14:00:06 INFO]: EssentialsXProtect version: 2.19.0-dev+226-17e026f
[14:00:06 INFO]: EssentialsXChat version: 2.19.0-dev+226-17e026f
[14:00:06 INFO]: EssentialsXAntiBuild version: 2.19.0-dev+226-17e026f
[14:00:06 INFO]: EssentialsXSpawn version: 2.19.0-dev+226-17e026f
[14:00:06 INFO]: Economy Layer: None
[14:00:06 INFO]: You are running unsupported plugins!
[14:00:06 INFO]: You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.
[14:00:06 INFO]: Fetching version information...
[14:00:06 INFO]: You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/24234105af3148f181f9b4599d95626e

### EssentialsX config files

https://paste.gg/p/anonymous/3268c383895141a6901ad601f3dc1de9

### Error log (if applicable)

https://paste.gg/p/anonymous/1734efd2ce784964b1120fcbfd5e5a89

### Bug description

When using latest dev version of EssentialsX, with Antibuild as well, any player can break the EnderCrystals by left clicking on them, even though they can't break any other block (as they don't have permission to).
I have disabled the Ender Crystal explosion in config.yml but that doesn't solve my issue as it only prevents player from doing other block/entity damage with the crystals, they can still destroy the crystal.
The error in the log happens exactly when any player decides to destroy an Ender Crystal.

### Steps to reproduce

Use paper 1.8.8 and latest EssX dev and try to break an Ender Crystal (even if you are OP, the error persits in console).

### Expected behaviour

There should be no error in the console and the players should not be able to destory the Ender Crystals.

### Actual behaviour

There's the above mentioned error in console and players without build permission can break the Ender Crystal.

### PR DESCRIPTION
**Pull request by JRoy**
Ugly fix but it works for now...

Fixes #4418

### CODE REVIEW

File: EssentialsAntiBuild/src/main/java/com/earth2me/essentials/antibuild/EssentialsAntiBuildListener.java [hunk 1]
```diff
@@ -274,29 +275,33 @@ public void onBlockEntityDamage(final EntityDamageByEntityEvent event) {
...
         } else if (event.getEntity() instanceof EnderCrystal) {
-            type = Material.END_CRYSTAL;
+            // There is no Material for Ender Crystals before 1.9.
+            type = EnumUtil.getMaterial("END_CRYSTAL");
         } else {
             return;
         }
 
-        if (prot.getSettingBool(AntiBuildConfig.disable_build) && !user.canBuild() && !user.isAuthorized("essentials.build") && !metaPermCheck(user, "break", type)) {
+        final boolean permCheck = type == null ? user.isAuthorized("essentials.build.break.END_CRYSTAL") : metaPermCheck(user, "break", type);
```
Comment (mdcfe) [inline EssentialsAntiBuild/src/main/java/com/earth2me/essentials/antibuild/EssentialsAntiBuildListener.java]: Relying on `type` being null feels iffy to me? Probably not an issue since the if/else above returns for any other entity though.

This also now performs the break perm check before the other perm checks and potentially after they've failed. Could maybe wrap in a lambda to avoid the early call?

**Review by mdcfe — APPROVED** [review]
