### PR TITLE
Discord: Respect game rule for advancement message type

### LINKED ISSUE #4865: ESSX Discord doesn't respect announceAdvancements gamerule when sending advancement message
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=638bef65de1c46f38e109c26a6d2a24a

### Error log (if applicable)

_No response_

### Bug description

Disabling the announceAdvancement gamerule still allows the advancement message through to Discord. Current server setup has two worlds, creative and survival.

I created a plugin to revoke advancements made while in creative mode (simplest solution without modifying Multiverse) and disabled announceAdvancements in the creative world, but the message gets displayed in the primary discord channel anyway. 

Ideally, advancement messages would still be enabled for the survival world, so disabling advancement messages on the bridge entirely is something I'd like to avoid.

Checking for whether or not the player's current world has the announceAdvancements gamerule enabled before sending the message would prevent this behaviour from occurring.

### Steps to reproduce

1. Disable announceAdvancements gamerule.
2. Complete an advancement.
3. Message still gets displayed in the channel, even though the message for in-game chat is disabled.

### Expected behaviour

Having the announceAdvancements gamerule disabled should prevent the message from appearing in discord.

### Actual behaviour

The message is displayed regardless of the player's current world's announceAdvancements gamerule value.

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #4865

### CODE REVIEW

File: EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/BukkitListener.java [hunk 1]
```diff
@@ -217,6 +217,11 @@ public void onAdvancement(AbstractAchievementEvent event) {
             return;
         }
 
+        if (VersionUtil.getServerBukkitVersion().isHigherThanOrEqualTo(VersionUtil.v1_13_0_R01)
+                && Boolean.FALSE.equals(event.getPlayer().getWorld().getGameRuleValue(GameRule.ANNOUNCE_ADVANCEMENTS))) {
```
Comment (mdcfe) [inline EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/BukkitListener.java:221]: Why

**Review by mdcfe — APPROVED** [review]
