### PR TITLE
Fix /tpr on legacy versions

### LINKED ISSUE #6211: TPR Not working at all
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=TKXFJM1Qxs

### Error log (if applicable)

no error logs

### Bug description

As said like 6 months ago, the TPR is not working anymore in 1.8.8 with the 2.21.X+ update.

### Steps to reproduce

Run a Spigot server under 1.8, and try to tpr. you'll see, nothing append.

### Expected behaviour

TPR to work.

### Actual behaviour

TPR not working.

### Additional Information

Issue already created 2 time this year, but you keep ignoring it.

### PR DESCRIPTION
**Pull request by JRoy**
Commodore breaks this on legacy likely, use a provider to ensure we use the old ABI...................i love legacy

Fixes #6211

### CODE REVIEW

File: providers/1_8Provider/src/main/java/net/ess3/provider/providers/LegacyBiomeNameProvider.java [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package net.ess3.provider.providers;
+
+import net.ess3.provider.BiomeNameProvider;
+import net.essentialsx.providers.ProviderData;
+import org.bukkit.block.Block;
+
+import java.util.Locale;
+
+@ProviderData(description = "Legacy Item Unbreakable Provider")
```
Comment (mdcfe) [inline providers/1_8Provider/src/main/java/net/ess3/provider/providers/LegacyBiomeNameProvider.java]:
```suggestion
@ProviderData(description = "Legacy Biome Name Provider")
```

**Comment by Koora7334** [comment]
Seems that u missed on the provider description

File: providers/1_8Provider/src/main/java/net/ess3/provider/providers/LegacyBiomeNameProvider.java [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+public class LegacyBiomeNameProvider implements BiomeNameProvider {
+    @Override
+    public String getBiomeName(final Block block) {
+        return block.getBiome().name().toLowerCase(Locale.ENGLISH);
```
Comment (mdcfe) [inline providers/1_8Provider/src/main/java/net/ess3/provider/providers/LegacyBiomeNameProvider.java:15]: Add a comment explaining what this is doing - compiling against an enum on 1.8 and relying on a Commodore rewrite / bytecode magic / ??? to work on latest

**Review by mdcfe — CHANGES_REQUESTED** [review]

File: providers/1_8Provider/src/main/java/net/ess3/provider/providers/LegacyBiomeNameProvider.java (hunk 2 above)
Comment (JRoy) [reply providers/1_8Provider/src/main/java/net/ess3/provider/providers/LegacyBiomeNameProvider.java:15]:
```suggestion
        // For some reason, compiling against modern versions causes this call to break, possibly related to OldEnum?
        // Compiling this against versions that still have proper enums allow this to work
        return block.getBiome().name().toLowerCase(Locale.ENGLISH);
```

**Review by mdcfe — APPROVED** [review]
