### PR TITLE
Fix /unlimited with changing stack sizes

### LINKED ISSUE #4819: /unlimited broken
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ea966c55856442989626f523b007fabb

### Error log (if applicable)

_No response_

### Bug description

After running the "/unlimited" command and placing something with more than 2 items it'll add more than one back to the stack. 

### Steps to reproduce

1. /Unlimited (block)
2. Place with more than 2 items in stack

### Expected behaviour

Add one item per one used

### Actual behaviour

Adds more than one item to the stack, hence overflowing into a new stack.

### PR DESCRIPTION
**Pull request by Deltric**
### Information

This PR fixes #4819 . 

### Details

**Proposed fix:**    

Clones the ItemStack with a new quantity of 1 to readd to their inventory.
This causes no net gain in items.

Before doing so it checks if the stack is not air which is caused by the player trying to place a block with a stack size of one. 
This is done to avoid an exception from setting stack size on empty and might avoid unnecessary updates.
Additionally feature behavior is unaltered as previously you still needed more than 1 block in an unlimited stack.

**Environments tested:**    

OS: Windows 11

Java version:  17.0.1

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**    

Before (Tested with EssentialsX 2.19.4 and 2.20.0-dev+4-4bd1b3c)
https://user-images.githubusercontent.com/25653276/160824043-5b329258-7938-4c22-8fdd-0de0049a1edf.mp4

After (Tested by using the compiled version with this commit)
https://user-images.githubusercontent.com/25653276/160824285-9be61d3e-0238-4647-b8e2-440fc32b569b.mp4

### CODE REVIEW

**Review by JRoy — APPROVED** [review]

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsBlockListener.java [hunk 1]
```diff
@@ -42,8 +43,12 @@ public void onBlockPlace(final BlockPlaceEvent event) {
         final User user = ess.getUser(event.getPlayer());
         if (user.hasUnlimited(is) && user.getBase().getGameMode() == GameMode.SURVIVAL) {
             ess.scheduleSyncDelayedTask(() -> {
-                user.getBase().getInventory().addItem(is);
-                user.getBase().updateInventory();
+                if(is.getType() != Material.AIR) {
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsBlockListener.java]:
```suggestion
                if(is != null && is.getType() != null && !MaterialUtil.isAir(is.getType())) {
```

**Review by JRoy — CHANGES_REQUESTED** [review]

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsBlockListener.java [hunk 2]
```diff
@@ -3,6 +3,7 @@
 import com.earth2me.essentials.utils.MaterialUtil;
 import net.ess3.api.IEssentials;
 import org.bukkit.GameMode;
+import org.bukkit.Material;
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsBlockListener.java]:
```suggestion
```

**Review by JRoy — CHANGES_REQUESTED** [review]

**Review by JRoy — DISMISSED** [review]

**Review by JRoy — APPROVED** [review]

**Comment by JRoy** [comment]
Thanks for the contribution!
