### PR TITLE
Fix spawner delay feature

### LINKED ISSUE #1332: Spawner delay only affects the first spawn
Spawner delay only seems to work for the first spawn.
Example: /spawner polarbear 5000
Takes a long time for the first spawn but spawns after that take the default delay.
Not sure if it's an issue with Essentials or maybe PaperSpigot which is what i'm using.

### PR DESCRIPTION
**Pull request by pop4959**
Closes #1332

The spawner delay feature has been broken in Essentials for as long as anyone can remember. The reasons for this are mentioned in the issue above.

This PR fixes this by changing the command to utilize new API for setting the minimum and maximum spawn delay on spawners. This API was added in 1.12.2, so all supported versions before that (1.8.8 thru 1.12.1) require NMS to function properly. I'm aware that Essentials avoids NMS for maintainability reasons, however that should not be of much concern here since all versions 1.12.2 and later are going to be using the Bukkit API. Hence, no NMS updates will be necessary.

Also let me know if you want the NMS code refactored somewhere else. I saw the net.ess3.nms packages, but I wasn't sure where this would fit into the organisation of that.

Tested on:
1.8.8, 1.9.4, 1.10.2, 1.11.2 (NMS)
1.12.2, 1.15.2 (Bukkit API)

### CODE REVIEW

File: Essentials/src/com/earth2me/essentials/commands/Commandspawner.java [hunk 1]
```diff
@@ -57,8 +62,31 @@ protected void run(final Server server, final User user, final String commandLab
...
+                    Object craftTileEntity = getTileEntityAt.invoke(block.getWorld(), block.getX(), block.getY(), block.getZ());
+                    Object nmsSpawner = getSpawner.invoke(craftTileEntity);
+                    Field minSpawnDelay = ReflUtil.getFieldCached(mobSpawnerAbstract, "minSpawnDelay");
+                    Field maxSpawnDelay = ReflUtil.getFieldCached(mobSpawnerAbstract, "maxSpawnDelay");
+                    if (minSpawnDelay != null && maxSpawnDelay != null) {
+                        minSpawnDelay.setInt(nmsSpawner, delay);
+                        maxSpawnDelay.setInt(nmsSpawner, delay);
+                    }
+                }
+            }
```
Comment (JRoy) [inline Essentials/src/com/earth2me/essentials/commands/Commandspawner.java]: All of the Class and Field objects should be stored as a `private static final` field. Additionally, the Method objects should be stored as a `MethodHandle`. 

See https://github.com/EssentialsX/Essentials/pull/3157/files#diff-d515c857ac85b710ac67491e3dd1779aR121-R148 for an example.

**Review by JRoy — DISMISSED** [review]

**Comment by mdcfe** [comment]
NMS should really be in providers - unfortunately the current naming convention of providers makes it difficult to know where to put them.

File: Essentials/src/com/earth2me/essentials/commands/Commandspawner.java (hunk 1 above)
Comment (pop4959) [reply Essentials/src/com/earth2me/essentials/commands/Commandspawner.java]: I overlooked this because I noticed `ReflUtil` already does a lot of the caching, but this is certainly a good idea. Also, didn't know about `MethodHandle`. From a quick google search, it looks like the main benefit there is it'll be a little faster to call than `Method`? I'll probably be refactoring this into it's own provider once I get some clarification from MD on how I should do that, so the NMS code won't just awkwardly be sitting inside Commandspawner.

**Comment by pop4959** [comment]
Yeah I took a glance at the existing provider system but it wasn't pretty. If I can get some advice with refactoring this spawner code into its own provider that would be neat. Another confusing thing is it seems like the "SpawnerProvider" doesn't really have anything to do with spawners either, so there's that...

**Comment by mdcfe** [comment]
As far as I can recall, the current "spawner providers" are for setting the entity type on stacks of spawners when they're spawned in. Perhaps the current spawner providers could be renamed to `SpawnerEntityProvider` and this could be implemented in an interface called `SpawnerDelayProvider`?

**Comment by pop4959** [comment]
@md678685 Sorry for the lack of updates, I did actually figure this out while looking deeper at the spawner provider code. It is indeed intended for accessing the entity type of a spawner ItemStack. My intention is to refactor the code of this PR into a provider (either the existing one, or split into its own as your are suggesting) to allow backwards compatibility with versions that don't have a complete CreatureSpawner API. Perhaps `SpawnerItemProvider` and `SpawnerBlockProvider` would be appropriate names?

I'm currently focusing on having #3279 resolved before I continue working on this (so I don't have to make further changes to the code).

**Comment by mdcfe** [comment]
> Perhaps `SpawnerItemProvider` and `SpawnerBlockProvider` would be appropriate names?

Sounds good.

**Review by mdcfe — APPROVED** [review]

File: nms/UpdatedMetaProvider/src/net/ess3/nms/updatedmeta/BukkitSpawnerBlockProvider.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+        spawner.setMaxSpawnDelay(delay);
+    }
+
+    @Override
+    public void setMinSpawnDelay(CreatureSpawner spawner, int delay) {
+        spawner.setMinSpawnDelay(delay);
+    }
+
+    @Override
+    public boolean tryProvider() {
```
Comment (mdcfe) [inline nms/UpdatedMetaProvider/src/net/ess3/nms/updatedmeta/BukkitSpawnerBlockProvider.java]: `tryProvider` should be implemented by the abstract provider class and should attempt to call one of the provider's methods. Otherwise we don't know for certain that this provider actually does what it's supposed to in a consistent fashion.

**Review by mdcfe — CHANGES_REQUESTED** [review]

File: nms/UpdatedMetaProvider/src/net/ess3/nms/updatedmeta/BukkitSpawnerBlockProvider.java (hunk 2 above)
Comment (pop4959) [reply nms/UpdatedMetaProvider/src/net/ess3/nms/updatedmeta/BukkitSpawnerBlockProvider.java]: Difficult to do in this circumstance, since we do not have a `CreatureSpawner` instance to call the provider's methods on. For the other providers, it's easier to do this since it only uses `ItemStack`, `EntityType` and `Material` classes, which are enums or easily instantiated. That's why I opted to implement `tryProvider` in the concrete class rather than in the abstract one. It's definitely different, but I don't think it's bad. The way it's set up, if the methods required from the API do not exist, we safely assume that this is MC 1.8-1.11, where we need NMS (old versions are not going to change). Otherwise, we can rely on the API (the implementation may change, but it should not concern us).

**Comment by pop4959** [comment]
Ready again for review - all issues resolved and tested

**Review by mdcfe — APPROVED** [review]
