### PR TITLE
Fix teleport request queue being reversed order

### LINKED ISSUE #4753: /tpaccept accepting first request instead of latest request.
### Type of bug

Exploit

### `/ess dump all` output

https://essentialsx.net/dump.html?id=a37828c4cf6946daa5103059ff358ae6

### Error log (if applicable)

_No response_

### Bug description

When a playerX accepts a tpa request `/tpaccept`, if playerX has multiple requests, the first request is accepted rather than the latest (expected behaviour). Players are using this to maliciously spam a few requests out and hope the requested players get a second request from some trusted player and accept. (which would then accept their request).

A temporary _sort of_ bandaid fix for my case is to set `tpa-accept-cancellation` to `5` rather then our usual `60`. Shortening this window allows for _less_ abuse.

I should note that if playerX has 2 requests and the first times out and the second is still _live_, when the playerX accepts, the first message they receive is that the first players request has timed out followed by a message indicating they accepted the second players request; the tpa of the second player goes through.

### Steps to reproduce

PlayerX, PlayerY, PlayerZ

1. PlayerY executes`/tpa PlayerX`
2. PlayerZ executes`/tpa PlayerX`
   _Both requests should not be timed out so set_ `tpa-accept-cancellation` _accordingly_
3. PlayerX executes `/tpaccept`

### Expected behaviour

PlayerZ's request should be granted.

### Actual behaviour

PlayerY's request is granted

### PR DESCRIPTION
**Pull request by JRoy**
Fix #4753

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/User.java [hunk 1]
```diff
@@ -349,11 +350,9 @@ public void requestTeleport(final User player, final boolean here) {
...
         teleportRequestQueue.remove(request.getName());
         if (teleportRequestQueue.size() >= ess.getSettings().getTpaMaxRequests()) {
-            String lastKey = null;
-            for (Map.Entry<String, TpaRequest> entry : teleportRequestQueue.entrySet()) {
-                lastKey = entry.getKey();
-            }
-            teleportRequestQueue.remove(lastKey);
+            final List<String> keys = new ArrayList<>(teleportRequestQueue.keySet());
+            Collections.reverse(keys);
+            teleportRequestQueue.remove(keys.get(0));
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/User.java]: Any reason to not just remove `keys.length() - 1`?

**Review by mdcfe — APPROVED** [review]

**Review by mdcfe — CHANGES_REQUESTED** [review]
oops

File: Essentials/src/main/java/com/earth2me/essentials/User.java (hunk 1 above)
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/User.java]:
```suggestion
            teleportRequestQueue.remove(keys.get(keys.size() - 1));
```

**Review by mdcfe — APPROVED** [review]
