### PR TITLE
Respect per player locale for command descriptions

### LINKED ISSUE #5841: Command Description string do not respect locale when not exist in the message config
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=624a170c9e294469b03506604bcbb935

### Error log (if applicable)

_No response_

### Bug description

To give an example, I have a message configuration in French, so all message descriptions and usages are not present in it.

EssentialsX correctly uses the messages it has in its jar to display in the same language except for commandDescription; it's the only message that defaults to English.

### Steps to reproduce

Set the `locale` option to `fr`, create a messages file config for french with only some message, don't include command description. 

### Expected behaviour

All message is style display in french from the default lang of the plugin

### Actual behaviour

commandDescription message is in english

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by iiAhmedYT**
### Information

This PR fixes #5841

### Details

**Proposed fix:**    
Simply use the already made per language description per command

**Environments tested:**    

OS: Windows

Java version:  

- [X] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**

Before:
Before

After:
After

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandhelp.java [hunk 1]
```diff
@@ -37,18 +37,19 @@ protected void run(final Server server, final User user, final String commandLab
...
+                        final boolean isEssCommand = bukkit instanceof PluginIdentifiableCommand && ((PluginIdentifiableCommand) bukkit).getPlugin().equals(ess);
                         user.sendTl("commandHelpLine1", cmd);
-                        user.sendTl("commandHelpLine2", knownCmd.getValue().getDescription());
-                        user.sendTl("commandHelpLine4", knownCmd.getValue().getAliases().toString());
+                        user.sendTl("commandHelpLine2", isEssCommand ? user.playerTl(bukkit.getName() + "CommandDescription") : bukkit.getDescription());
+                        user.sendTl("commandHelpLine4", bukkit.getAliases().toString());
                         user.sendTl("commandHelpLine3");
-                        final boolean isEssCommand = knownCmd.getValue() instanceof PluginIdentifiableCommand && ((PluginIdentifiableCommand) knownCmd.getValue()).getPlugin().equals(ess);
-                        final IEssentialsCommand essCommand = isEssCommand ? ess.getCommandMap().get(knownCmd.getValue().getName()) : null;
+                        final IEssentialsCommand essCommand = isEssCommand ? ess.getCommandMap().get(bukkit.getName()) : null;
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandhelp.java]: move this check up instead of using the PluginIdentifiableCommand cast check.

File: Essentials/src/main/java/com/earth2me/essentials/Essentials.java [hunk 2]
```diff
@@ -903,7 +903,7 @@ public boolean onCommandEssentials(final CommandSender cSender, final Command co
             } catch (final NotEnoughArgumentsException ex) {
                 if (getSettings().isVerboseCommandUsages() && !cmd.getUsageStrings().isEmpty()) {
                     sender.sendTl("commandHelpLine1", commandLabel);
-                    sender.sendTl("commandHelpLine2", command.getDescription());
+                    sender.sendTl("commandHelpLine2", sender.tl(command.getName() + "CommandDescription"));
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/Essentials.java]: this will throw a `MissingResourceException` if the user's locale doesn't have a translation for the given description string, maybe do something like this


```suggestion
                    String description = command.getDescription();
                    try {
                        description = sender.tl(command.getName() + "CommandDescription");
                    } catch (MissingResourceException ignored) {
                    }
                    sender.sendTl("commandHelpLine2", description);
```

**Review by JRoy — CHANGES_REQUESTED** [review]
This will not work if components are

**Comment by iiAhmedYT** [comment]
Will continue this once im home (im like 5 hours away)

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandhelp.java [hunk 3]
```diff
@@ -37,18 +37,19 @@ protected void run(final Server server, final User user, final String commandLab
                 final String cmd = pageStr.substring(1);
                 for (final Map.Entry<String, Command> knownCmd : ess.getKnownCommandsProvider().getKnownCommands().entrySet()) {
                     if (knownCmd.getKey().equalsIgnoreCase(cmd)) {
+                        final Command bukkit = knownCmd.getValue();
+                        final boolean isEssCommand = bukkit instanceof PluginIdentifiableCommand && ((PluginIdentifiableCommand) bukkit).getPlugin().equals(ess);
+                        final IEssentialsCommand essCommand = isEssCommand ? ess.getCommandMap().get(bukkit.getName()) : null;
                         user.sendTl("commandHelpLine1", cmd);
-                        user.sendTl("commandHelpLine2", knownCmd.getValue().getDescription());
-                        user.sendTl("commandHelpLine4", knownCmd.getValue().getAliases().toString());
+                        user.sendTl("commandHelpLine2", essCommand == null ? bukkit.getDescription() : user.playerTl(bukkit.getName() + "CommandDescription"));
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandhelp.java]: make sure you catch the exception here like you did in the other class

File: Essentials/src/main/java/com/earth2me/essentials/Essentials.java [hunk 4]
```diff
@@ -146,16 +146,7 @@
...
-import java.util.Collection;
-import java.util.Collections;
-import java.util.HashMap;
-import java.util.LinkedHashSet;
-import java.util.List;
-import java.util.Locale;
-import java.util.Map;
-import java.util.Set;
-import java.util.UUID;
+import java.util.*;
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/Essentials.java]: please don't use wildcard imports

**Review by JRoy — CHANGES_REQUESTED** [review]
few things and then should be good

File: Essentials/src/main/java/com/earth2me/essentials/Essentials.java (hunk 4 above)
Comment (iiAhmedYT) [reply Essentials/src/main/java/com/earth2me/essentials/Essentials.java]: sorry this automatically happened

File: Essentials/src/main/java/com/earth2me/essentials/Essentials.java [hunk 5]
```diff
@@ -145,15 +145,15 @@
 import org.bukkit.scheduler.BukkitTask;
 
 import java.io.File;
-import java.io.IOException;
-import java.util.ArrayList;
+import java.io.IOException;import java.util.ArrayList;
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/Essentials.java]:
```suggestion
import java.io.IOException;
import java.util.ArrayList;
```

**Review by JRoy — APPROVED** [review]

**Comment by JRoy** [comment]
Thanks for the contribution :)
