### PR TITLE
Prevent dragging items outside of invsee

### LINKED ISSUE #3065: Items are randomly swapped and deleted when using invsee
## Information

**Full output of `/ess version`**:

```Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-132 (MC: 1.15.2)
EssentialsX version: 2.17.1.62
LuckPerms version: 5.0.72
PlaceholderAPI version: 2.10.4
Vault version: 1.7.2-b107
Towny version: 0.95.2.0
EssentialsXChat version: 2.17.1.62
EssentialsXGeoIP version: 2.17.1.62
EssentialsXSpawn version: 2.17.1.62
```

**Server log**: [I can't begin to explain why, but for some reason, logs haven't generated in my logs folder since the 3rd of March. It's the 12th and I've been running the server daily for about a week. Luckily, I kept the terminal open and I will copy and paste from there and call it latest.log.](https://gist.github.com/emkirsh/d444bf182ed3080bf29093e239d3e0e1)

**EssentialsX config**: [My EssentialsX Config](https://gist.github.com/emkirsh/a509167566d144c564d6e001bd0f69d4)

## Details

**Description**  
So, pretty much, I was invsee-ing my alt, which was AFK fishing, to transfer items without going through the teleporting and re-setting the AFK fisher. I saw a few items glitching, but then it was fine. (or so I thought). Then, a few minutes later, I noticed my pickaxe had the wrong durability. After looking through and double-checking my inventory, I realized I only had one! I had originally had two pickaxes because I was planning on merging enchants in an anvil. I didn't even have the good one! So, I recreated the problem and found out that *when moving around items from one slot to another, sometimes they will be placed, seemingly at random, in another spot, and if there's already an item there, the original item gets deleted. Permanently. This happens more when you are moving the items quickly.*

###### One other thing, when looking at the emeralds in the video clip: When I accidentally discovered this, my emeralds disappeared. I found them in my alt's off-hand, which is quite strange considering the fact that off-hands aren't supported in */invsee*.

**Steps to reproduce**  
1. */invsee* someone.
2. move an item in your inventory from one spot to another, preferably quickly.
3. watch as the items are randomly switched to a different spot
   1. if the items are switched to a slot that already has an item, it will replace the original item, deleting it permanently. clicking all of the empty slots brings no luck.
4. hope you record it so you can spawn back the right enchants on your items, or you're out of luck 😉!
5. report it so it gets fixed.

**Expected behavior**  
I would expect the */invsee* command to work normally (as intended), and not delete my items when I move them.

**Screenshots**  
Here is a gif hosted on gyazo of this happening. Please disregard the log of me enchanting items. That was just me respawning the items from my first time. 
## Let me know if you need anything else! Thanks and have a nice night. I hope everything's okay with Coronavirus and stuff, and I understand if the response is a bit slow amidst all this. Thanks! 
# -emkirsh

### PR DESCRIPTION
**Pull request by tanyaofei**
Fixes #3065

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java [hunk 1]
```diff
@@ -40,10 +40,7 @@
 import org.bukkit.event.EventHandler;
 import org.bukkit.event.EventPriority;
 import org.bukkit.event.Listener;
-import org.bukkit.event.inventory.ClickType;
-import org.bukkit.event.inventory.InventoryClickEvent;
-import org.bukkit.event.inventory.InventoryCloseEvent;
-import org.bukkit.event.inventory.InventoryType;
+import org.bukkit.event.inventory.*;
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java]:
```suggestion
import org.bukkit.event.inventory.ClickType;
import org.bukkit.event.inventory.Inventory;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.inventory.InventoryType;
```

**Comment by JRoy** [comment]
still need to test this but at first glance I'd want to remove the use of streams + use the `isArmorSlot` method in the `com.earth2me.essentials.craftbukkit.Inventories` class to make it more clear what is going on in this code.

**Comment by tanyaofei** [comment]
I have commit new codes, but one thing to note is that this listener does not only cancel the event of dragging into armor slots but also all events of dragging into the bottom inventory. This is because the slot on the client side does not match the slot on the server side, if not so, the item may appear in a slot that was not dragged to or disappear.

**Review by JRoy — APPROVED** [review]
Thanks for figuring this out! Appreciate it!
