### PR TITLE
Fix flight ability preservation between worlds

### LINKED ISSUE #6041: Fly restet by World change
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=rYGsbMGgUF

### Error log (if applicable)

_No response_

### Bug description

We currently have the issue that when we switch worlds, for example from the Spawn to the OneBlock world, the flight is reset every time. So, we currently have to type /fly again each time.

**Server Version:** 1.20.6
**EssentialsX Version:** EssentialsX-2.21.0-dev+167-4e64782.jar

Config Settings:
**world-change-fly-reset:** false
**world-change-speed-reset:** true

Player Permission:
essentials.fly.safelogin true
essentials.fly true

Permission System LuckPerms

### Steps to reproduce

no message..

### Expected behaviour

Flight should be automatically enabled upon joining.
Flight should be retained when switching between worlds.

### Actual behaviour

no message..

### Additional Information

no message..

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #6041

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java [hunk 1]
```diff
@@ -778,9 +782,12 @@ public void onPlayerChangedWorldFlyReset(final PlayerChangedWorldEvent event) {
         }
 
         final TickCountProvider tickCountProvider = ess.provider(TickCountProvider.class);
-        if (tickCountProvider != null && user.getFlightTick() == tickCountProvider.getTickCount() && user.isAuthorized("essentials.fly")) {
+        final int flightTick = user.getFlightTick();
+        if (tickCountProvider != null && Math.abs(flightTick) == tickCountProvider.getTickCount() && user.isAuthorized("essentials.fly")) {
             user.getBase().setAllowFlight(true);
-            user.getBase().setFlying(true);
+            if (Integer.signum(flightTick) == 1) {
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java]: Is there any reason to use `Integer.signum` over checking `> 0`?

**Review by mdcfe — CHANGES_REQUESTED** [review]

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java (hunk 1 above)
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java]:
```suggestion
            if (flightTick > 0) {
```

**Review by mdcfe — APPROVED** [review]
