### PR TITLE
Properly handle jail respawn in togglejail (Fixes #3520)

### LINKED ISSUE #3520: When freed from jail players are teleporting back to previous position
### Information

**Full output of `/ess version`**:
```
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-83 (MC: 1.16.1).
EssentialsX version: 2.18.0.0.
LuckPerms version: 5.0.72.
Vault version: 1.7.2-b107.
EssentialsXChat version: 2.18.0.0.
```
**Server log**: https://gist.github.com/Magiks21/c6f8466ffe6272916684b7dd9019bf6d
**Essentials Config**: https://gist.github.com/Magiks21/009fd6c5ea137fb753e8ae712d20e80a

### Details

**Description**  
Despite having the teleport-back-when-freed-from-jail node set to "false" in the configuration, players are still being returned to previous position.

**Steps to reproduce**  
Set teleport-back-when-freed-from-jail node to "false". Jail Player. Unjail Player.

**Expected behavior**  
Player is not teleported back to previous position

**Screenshots**
Player Returning to previous position 2000+ blocks from jail

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #3520

### CODE REVIEW

File: Essentials/src/com/earth2me/essentials/commands/Commandtogglejail.java [hunk 1]
```diff
@@ -101,14 +102,19 @@ public void run(final Server server, final CommandSource sender, final String co
...
-                if (player.getBase().isOnline()) {
+                if (player.getBase().isOnline() && ess.getSettings().isTeleportBackWhenFreedFromJail()) {
                     CompletableFuture<Boolean> future = getNewExceptionFuture(sender, commandLabel);
                     player.getAsyncTeleport().back(future);
                     future.thenAccept(success -> {
                         if (success) {
                             sender.sendMessage(tl("jailReleased", player.getName()));
                         }
                     });
+                    future.exceptionally(e -> {
```
Comment (montlikadani) [inline Essentials/src/com/earth2me/essentials/commands/Commandtogglejail.java:113]: Not better to call this after `thenAccept`?

```suggestion
future.thenAccept(success -> {
                        if (success) {
                            sender.sendMessage(tl("jailReleased", player.getName()));
                        }
                    }).exceptionally(e -> {
```

Comment (JRoy) [reply Essentials/src/com/earth2me/essentials/commands/Commandtogglejail.java:113]: `thenAccept`/`exceptionally` both return Voided CompletionStages which cannot be chained

**Review by pop4959 — APPROVED** [review]
Assuming this has been tested, looks OK.

**Review by mdcfe — APPROVED** [review]
