### PR TITLE
Prevent legacy material support from being initiated

### LINKED ISSUE #4671: Legacy support started by calls to Block#getData + ItemStack#getDurability
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3038e461ed7f43b1b3166f7b5b15ed97

### Error log (if applicable)

https://pastebin.com/d9izsaRt

### Bug description

When interacting with a Door/Pressure Plate/Lectern/Sign (for warping)

Server locks up and starts legacy support. Causes a bit of log. Happens at least once per restart.

Tested on multiple builds and the current dev build. Happens on previous versions of paper, and fresh installs. 

Only plugins used are Luck perms, and Multiverse. Happens away from any spawn protections that could be setup. 

Happens on both Regular User and Operator interactions. 

### Steps to reproduce

When interacting with a Door/Pressure Plate/Lectern/Sign (for warping)

Sometimes will trigger it. It normally happens with in the first hour

### Expected behaviour

Not to start legacy support

### Actual behaviour

Starts legacy support

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #4671

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandcondense.java [hunk 1]
```diff
@@ -161,8 +164,7 @@ private SimpleRecipe getCondenseType(final ItemStack stack) {
                 iter.remove();
                 continue;
             }
-
-            if (inputSlot.getDurability() == Short.MAX_VALUE) {
+            if (legacy && inputSlot.getDurability() == Short.MAX_VALUE) {
```
Comment (Octol1ttle) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandcondense.java]: Why create a variable when it's only used once? You should do this in `Trade.java` instead

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java [hunk 2]
```diff
@@ -111,13 +111,14 @@ public void shapedRecipe(final CommandSource sender, final ShapedRecipe recipe,
             final InventoryView view = user.getBase().openWorkbench(null, true);
             final String[] recipeShape = recipe.getShape();
             final Map<Character, ItemStack> ingredientMap = recipe.getIngredientMap();
+            final boolean legacy = VersionUtil.getServerBukkitVersion().isLowerThan(VersionUtil.v1_13_0_R01);
```
Comment (Octol1ttle) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java]: Same issue as in Condense, use a global variable like you did in MaterialUtil

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandrepair.java [hunk 3]
```diff
@@ -39,7 +40,7 @@ public void run(final Server server, final User user, final String commandLabel,
 
     public void repairHand(final User user) throws Exception {
         final ItemStack item = user.getItemInHand();
-        if (item == null || item.getType().isBlock() || item.getDurability() == 0) {
+        if (item == null || item.getType().isBlock() || (MaterialUtil.getDamage(item) == 0)) {
```
Comment (Octol1ttle) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandrepair.java]:
```suggestion
        if (item == null || item.getType().isBlock() || MaterialUtil.getDamage(item) == 0) {
```

File: Essentials/src/main/java/com/earth2me/essentials/utils/MaterialUtil.java [hunk 4]
```diff
@@ -129,20 +132,12 @@ public static boolean isLeatherArmor(final Material material) {
...
-
-    public static boolean isPlayerHead(final Material material, final int durability) {
-        if (PLAYER_HEADS.contains(material)) {
+    public static boolean isPlayerHead(final ItemStack stack) {
+        if (PLAYER_HEADS.contains(stack.getType())) {
             return true;
         }
 
-        return LEGACY_SKULLS.contains(material) && durability == 3;
+        return VersionUtil.getServerBukkitVersion().isLowerThan(VersionUtil.v1_13_0_R01) && LEGACY_SKULLS.contains(stack.getType()) && stack.getDurability() == 3;
```
Comment (Octol1ttle) [inline Essentials/src/main/java/com/earth2me/essentials/utils/MaterialUtil.java]:
```suggestion
        return PRE_FLATTEN && LEGACY_SKULLS.contains(stack.getType()) && stack.getDurability() == 3;
```

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandcondense.java (hunk 1 above)
Comment (mdcfe) [reply Essentials/src/main/java/com/earth2me/essentials/commands/Commandcondense.java]: @l1ttleO It is far more readable with a variable than with inlined version checks everywhere.

In theory this could be a static field, but I'll leave it to @JRoy to make that change if he decides to.

Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/commands/Commandcondense.java]: Because otherwise we'd be repeating the same check in a loop which isn't cheap

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java (hunk 2 above)
Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java]: Same

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandcondense.java [hunk 5]
```diff
@@ -153,6 +154,8 @@ private SimpleRecipe getCondenseType(final ItemStack stack) {
             return null;
         }
 
+        final boolean legacy = VersionUtil.getServerBukkitVersion().isLowerThan(VersionUtil.v1_13_0_R01);
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandcondense.java]: With the sheer amount of VersionUtil calls just to determine whether we're on a pre-flattening or post-flattening version, would it be worth throwing a static `POST_FLATTENING` field on `VersionUtil` for the sake of readability?

**Review by mdcfe — DISMISSED** [review]

**Review by pop4959 — APPROVED** [review]
