### PR TITLE
Player should not be able to send empty shout/question messages

### LINKED ISSUE #3317: Empty shout double charges user
**Information**
Essentials version

[22:47:32 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-304 (MC: 1.15.2)
[22:47:32 INFO]: EssentialsX version: 2.17.2.99
[22:47:32 INFO]: Vault version: 1.7.2-b107
[22:47:32 INFO]: EssentialsXChat version: 2.17.2.99

**latest.log** https://gist.github.com/SMD404/b6d814b027b4738f6707f482bc96edfc
**EssentialsX** config: https://gist.github.com/SMD404/fb72b6aaee2a8bd86a57a800702c4dfc

**Description**  
Hello, i use cost for global chat, and when a player sends to chat "!" without message, then they pay double price. 

**Steps to reproduce**  
Message in chat as in the screenshot (! and no message - chat local + double price, ! and message - chat global + normal price)

**Expected behavior**  
! - There should be no fee for local chat (BUG)
! + message - everything is working

**Screenshots**  
https://i.imgur.com/EcgqsoG.png

### PR DESCRIPTION
**Pull request by pop4959**
This is nonsense behavior, especially as the function that handles this doesn't allow empty messages for normal chat, so empty shout/question messages are also invalid.

Fixes #3317

### CODE REVIEW

File: EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChatPlayer.java [hunk 1]
```diff
@@ -38,9 +38,9 @@ String getChatType(final String message) {
 
         final char prefix = message.charAt(0);
         if (prefix == ess.getSettings().getChatShout()) {
-            return "shout";
+            return message.length() > 1 ? "shout" : "";
```
Comment (montlikadani) [inline EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChatPlayer.java:41]:
```suggestion
!message.isEmpty() ? "shout" : "";
```
See this for proof: https://stackoverflow.com/a/19126404

Comment (pop4959) [reply EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChatPlayer.java:41]: `message` here includes the prefix character, which means a valid shout needs to be at least two characters total, since this gets removed later.

**Review by JRoy — APPROVED** [review]
