### PR TITLE
Do not lowercase afk timeout commands

### LINKED ISSUE #6254: New config.yml option: afk-timeout-command: (#6169) doesn't parse the {USERNAME} placeholder
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=Fw8oh3F9le

### Error log (if applicable)

-

### Bug description

Basically tried several commands in the new afk command option, but the provided {USERNAME} placeholder doesn't parse to the actual playername, I also tried papi placeholders such as player_name and what not, but none worked either as it prolly doesn't parse papi in it.

### Steps to reproduce

Update to the latest dev build and regen den config.
Enable the provided kick example
Set afk thresholds to lower values and test ingame

### Expected behaviour

To parse the provided {USERNAME} as the actual username rather than the text.

### Actual behaviour

See bug description.

### Additional Information

Example with kick outputs this:
[20:23:05 INFO]: [Essentials] CONSOLE issued server command: /kick {username}

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #6254

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/Settings.java [hunk 1]
```diff
@@ -1271,7 +1271,7 @@ public long getAutoAfkTimeout() {
     private Set<String> _getAfkTimeoutCommands() {
         final Set<String> timeoutCommands = new HashSet<>();
         for (final String cmd : config.getList("afk-timeout-commands", String.class)) {
-            timeoutCommands.add(cmd.toLowerCase(Locale.ENGLISH));
+            timeoutCommands.add(cmd);
```
Comment (mdcfe) [inline Essentials/src/main/java/com/earth2me/essentials/Settings.java]: We should really store a list, not a set, as this will break the expected execution order (and repeated commands, though that's less of a concern)

**Review by mdcfe — CHANGES_REQUESTED** [review]

**Review by mdcfe — APPROVED** [review]
