### PR TITLE
Fix incorrect /me behaviour in local chat

### LINKED ISSUE #3834: The / me command works in the wrong radius if you set the chat radius.
**Full output of /ess version:**

>.... [16:47:30 INFO]: Server version: 1.16.3-R0.1-SNAPSHOT git-Tuinity-"de1983b" (MC: 1.16.3)
>.... [16:47:30 INFO]: EssentialsX version: 2.18.1.32
>.... [16:47:30 INFO]: PlaceholderAPI version: 2.10.9
>.... [16:47:30 INFO]: LuckPerms version: 5.2.23
>.... [16:47:30 INFO]: Vault version: 1.7.3-b131
>.... [16:47:30 INFO]: EssentialsXChat version: 2.18.1.32
>.... [16:47:30 INFO]: EssentialsXSpawn version: 2.18.1.32
>.... [16:47:30 INFO]: You are running an unsupported server version!

**Server startup log:**
https://gist.github.com/GrigSolar/76be7b0704a0f94a7798766ad8fc43b3

**EssentialsX config:**
https://gist.github.com/GrigSolar/9b32638ae9965445a5d30f5ed68982f8

**Description:**
When I set the chat radius to 40 in the config file, the visibility range of the /me command is significantly reduced. After trying to set different values, I realized that the radius /me is the right size if you set the chat radius to (radius /me * (radius /me + 1)). That is, for /me to work on 40 blocks, you need to set the chat radius to 1640 blocks.

**Steps to reproduce:**
Write command /me.

**Expected behavior:**
Visibility of text from the /me command in a radius equal to the chat radius.

### PR DESCRIPTION
**Pull request by triagonal**
### Information

This PR fixes #3834, where /me does not correctly respect the local chat radius if one is set.

### Details

**Proposed fix:**    
This PR adds the missing operation to square the chat radius before comparing it. This operation is present in EssentialsXChat's local chat listener, but was left out here.

**Environments tested:**    
- [x] [Latest](https://papermc.io/downloads) Paper Version (any OS, any Java 8+ version)

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandme.java [hunk 1]
```diff
@@ -40,12 +40,13 @@ public void run(final Server server, final User user, final String commandLabel,
         message = FormatUtil.formatMessage(user, "essentials.chat", message);
 
         user.setDisplayNick();
-        final int radius = ess.getSettings().getChatRadius();
+        long radius = ess.getSettings().getChatRadius();
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandme.java:43]:
```suggestion
        final long radius = ess.getSettings().getChatRadius();
```
codestyle sadge

**Review by JRoy — APPROVED** [review]

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandme.java (hunk 1 above)
Comment (triagonal) [reply Essentials/src/main/java/com/earth2me/essentials/commands/Commandme.java:43]: I change this value on line 49, so I can't make it final here.

Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/commands/Commandme.java:43]: misread, ignore

**Review by pop4959 — APPROVED** [review]
