### PR TITLE
Fix /pay working on vanished players

### LINKED ISSUE #4113: Players using /pay to check if staff are vanished.
### Type of bug

Exploit

### `/ess version` output

[12:24:27 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Purpur-967 (MC: 1.16.5)                                       
[12:24:27 INFO]: EssentialsX version: 2.19.0-dev+101-0668e4c                                                            
[12:24:27 INFO]: LuckPerms version: 5.2.76                                                                              
[12:24:27 INFO]: Vault version: 1.7.3-b131                                                                              
[12:24:27 INFO]: EssentialsXChat version: 2.19.0-dev+101-0668e4c                                                        
[12:24:27 INFO]: EssentialsXSpawn version: 2.19.0-dev+101-0668e4c                                                      
[12:24:27 INFO]: Fetching version information...                                                                       
[12:24:27 INFO]: You're 3 EssentialsX dev build(s) out of date!                                                         
[12:24:27 INFO]: Download it here: https://essentialsx.net/downloads.html 

### Server startup log

https://paste.gg/p/anonymous/4ace0eb27e7841e98e712e779d08b4b1

### EssentialsX config files

//

### Error log (if applicable)

_No response_

### Bug description

When a staff member is vanished using essentials /ev or supervanish /sv, regular players can "test" if they are online by using /pay. If they are online but vanished the transaction goes through and reveals their presence.

### Steps to reproduce

1. Have two players online
2. Have one player vanish
3. Have the other player (without vanish/see vanished player permissions) /pay <vanished players username> 10
4. The vanished player receives the money and the sender gets a notification saying "$10 has been sent to <vanished player's name>

### Expected behaviour

The sender should not be able to send money to vanished players. The correct message should be "You cannot pay offline users"

### Actual behaviour

The transaction goes through even when the recipient is vanished, alerting the sender that the staff member is online but vanished

### PR DESCRIPTION
**Pull request by Octol1ttle**
### Information

This PR fixes #4113  

### Details

**Proposed fix:**    

The fix was to check if the user is hidden using `User#isHidden(Player)` in the "player is offline" check

**Environments tested:**    
**Tested by the author of #4113**

OS: Windows 10

Java version: AdoptOpenJDK 11.0.10+9 2021-01-19

- [x] git-Purpur-967 (MC: 1.16.5)

**Demonstration:**    

Before:
image
After:
image

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/commands/Commandpay.java [hunk 1]
```diff
@@ -50,7 +50,7 @@ public void run(final Server server, final User user, final String commandLabel,
         }
         loopOfflinePlayersConsumer(server, user.getSource(), false, user.isAuthorized("essentials.pay.multiple"), args[0], player -> {
             try {
-                if (player.getBase() != null && !player.getBase().isOnline() && !canPayOffline) {
+                if (player.getBase() != null && !player.getBase().isOnline() && !canPayOffline || player.isHidden(user.getBase()) && !canPayOffline) {
```
Comment (JRoy) [inline Essentials/src/main/java/com/earth2me/essentials/commands/Commandpay.java]:
```suggestion
                if (player.getBase() != null && (!player.getBase().isOnline() || player.isHidden(user.getBase())) && !canPayOffline) {
```

**Review by JRoy — CHANGES_REQUESTED** [review]
~~~~

**Review by JRoy — APPROVED** [review]

**Comment by JRoy** [comment]
Thanks
