### PR TITLE
Fix sulk sensors detecting vanished players

### LINKED ISSUE #5144: Sulk sensors can detect vanish players
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3fd4b82106e841ab9c0ebf70ed2df771

### Error log (if applicable)

_No response_

### Bug description

Players in vanish are detected by sulk sensors if they make noise.
They can therefore be detected by other players and spawn wardens

### Steps to reproduce

set yourself in vanish (/vanish)
find an ancient city (/minecraft:locate structure minecraft:ancient_city) and teleport to it
walk around sulk sensors and sulk shrieker
sulk sensors will play their sound and a warden may spawn

### Expected behaviour

sulk sensors should not detect the vanished player

### Actual behaviour

sulk sensors detects the vanished player

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #5144

### CODE REVIEW

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java [hunk 1]
```diff
@@ -121,13 +121,26 @@ private static boolean isArrowPickupEvent() {
         }
     }
 
+    private static boolean isGameEventEvent() {
+        try {
+            Class.forName("org.bukkit.event.block.BlockReceiveGameEvent");
+            return true;
```
Comment (pop4959) [inline Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java:127]: Can we cache this result (e.g. from a static block) to avoid reflection constantly.

**Review by pop4959 — CHANGES_REQUESTED** [review]

File: Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java (hunk 1 above)
Comment (JRoy) [reply Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java:127]: only called during registration, once, on startup.

**Review by pop4959 — APPROVED** [review]
